### ISSUE TITLE
there is an error in the web inspector and i can't add any cfg in the index.jsx cuz it's in no use

### ISSUE THREAD

**Issue by aws0me** [roele/istats.widget#25] opened 2019-06-19 16:30 UTC
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the top-level render call using <div>. See https://fb.me/react-warning-keys for more information.
    in div

**Comment by roele** [comment] 2019-06-20 16:17
Can you confirm the version (e.g. 2.0.0) you're using and elaborate on the issues with the configuration?

**Comment by roele** [comment] 2019-07-14 18:46
I'm unable to reproduce this issue with not further information, hence closing.

**Closed as completed by roele** 2019-07-14 18:46 UTC
Labels: bug, invalid
