### ISSUE TITLE
OSX El Capitan

### ISSUE THREAD

**Issue by techassistant** [roele/istats.widget#8] opened 2016-05-12 00:54 UTC
This doesn't work nothing shows up I'm new to Übersicht

**Comment by Metal-Snake** [comment] 2016-05-12 07:21
works fine on El Capitan.

what happens when you enter

```
istats
```

 into the terminal?

**Comment by roele** [comment] 2016-05-12 07:36
@techassistant This might be a known issue (#7). Did you try the workaround mentioned in #7 replacing the command?

I'd appreciate some more details about your setup (OS/Ruby version, Env variables etc.)

**Comment by techassistant** [comment] 2016-05-15 23:23
When I type istats it shows me my CPU temp and fan speeds I tried issue #7 and it did not work  how do I find the ruby version and env variables sorry I am new to all of this.

**Comment by roele** [comment] 2016-06-12 09:49
Closing as duplicate of #7

**Closed as completed by roele** 2016-06-12 09:49 UTC
Labels: duplicate
